In [1]:
#loading from the toolkit dir
import sys
sys.path.insert(0, r'/Users/gpa_18/Documents/Python/Toolkit')

import excelload
from os import path

In [2]:
loc = path.realpath(r"C:\Users\Gpardo\Documents\ToSearchURL.xlsx")
test = excelload.loadexcel(loc)
test.head()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/gpa_18/Documents/Python/Testing Area/C:\\Users\\Gpardo\\Documents\\ToSearchURL.xlsx'

In [3]:
product_detail = path.realpath(r"C:\Users\Gpardo\Desktop\proyecto_test\product_detail.csv")
sku = path.realpath(r"C:\Users\Gpardo\Desktop\proyecto_test\sku_per_transaction.csv")
transaction = path.realpath(r"C:\Users\Gpardo\Desktop\proyecto_test\TransactionID_perUser.csv")

product_df = excelload.loadcsv(product_detail )
sku_df = excelload.loadcsv(sku)
transID_df = excelload.loadcsv(transaction)
print(product_df.head())
print(sku_df.head())
print(transID_df.head())

How do you want to split the data, usually is with a comma?
Write your separator?
The default value is ,
Where the headers are located? 0
How do you want to split the data, usually is with a comma?
Write your separator?
The default value is ,
Where the headers are located? 0
How do you want to split the data, usually is with a comma?
Write your separator?
The default value is ,
Where the headers are located? 0
        SKU                        Name
0  10027097                MAC BROW SET
1  10028673          MAC BRUSH CLEANSER
2  10032289          MAC CONCEALER NW25
3  10034199  MAC EYE SHADOW SMALL BRULE
4  10068882   ANIS DEL MONO DULCE 750ML
          ID  Transaction_Revenue  qty       SKU
0  100170606               1526.4    1  38923238
1  100170606               1526.4    1  38855010
2  100182649               3570.5    1  39101609
3  100182649               3570.5    1  38976508
4  100182649               3570.5    1  38681348
          ID    UserID
0  100170606  682843.0
1  100182649  310244.0
2  100201437  337205.0
3  100203854  273340.0
4  100209084       NaN

In [4]:
Trans_per_user = sku_df.merge(transID_df, on='ID')
trans_with_name = Trans_per_user.merge(product_df, on='SKU')
trans_with_name.reset_index()
print(len(trans_with_name))
trans_with_name.head()

8262

,ID,Transaction_Revenue,qty,SKU,UserID,Name
0,100182649,3570.5,1,38681348,310244.0,"VESTIDO DETALLE DE AGU ROJO,MED"
1,100203854,3858.7,1,38720151,273340.0,"VESTIDO DOBLE RAYAS NEGRO CON OT,10"
2,100203854,3858.7,1,18121408,273340.0,LABIAL 16 YSL ROUGE PUR COUTURE ROUGE RO
3,100203854,3858.7,1,38413651,273340.0,BOTIN DAIS01S1017 BLACK NEGRO24 1/2
4,100512293,849.5,1,38413651,674984.0,BOTIN DAIS01S1017 BLACK NEGRO24 1/2

In [27]:
final_db = trans_with_name.dropna()
print(len(final_db))
final_db.head()

7168

,ID,Transaction_Revenue,qty,SKU,UserID,Name
0,100182649,3570.5,1,38681348,310244.0,"VESTIDO DETALLE DE AGU ROJO,MED"
1,100203854,3858.7,1,38720151,273340.0,"VESTIDO DOBLE RAYAS NEGRO CON OT,10"
2,100203854,3858.7,1,18121408,273340.0,LABIAL 16 YSL ROUGE PUR COUTURE ROUGE RO
3,100203854,3858.7,1,38413651,273340.0,BOTIN DAIS01S1017 BLACK NEGRO24 1/2
4,100512293,849.5,1,38413651,674984.0,BOTIN DAIS01S1017 BLACK NEGRO24 1/2

In [6]:
# Creating ratings based on ideas

In [28]:
import numpy as np
from numpy import float32
import pandas as pd

a=.7 #3
b=1-a

final_db['price'] = final_db['Transaction_Revenue'].div(final_db['qty'])
print(len(final_db))
Db_sans_1 = final_db[final_db['price']>1]

Db_sans_1['ratings'] = np.log(Db_sans_1['qty'])*a + np.log(Db_sans_1['price'])*b
Db_sans_1.reset_index(inplace=True,drop=True)

Db_sans_1.sort_values(by='ratings',ascending=False).head()

7168

C:\Users\Gpardo\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Gpardo\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

,ID,Transaction_Revenue,qty,SKU,UserID,Name,price,ratings
809,100507562,280653.56,22,38157599,352342.0,TV LG 55P UHD 55UJ6520,12756.98,4.999880
6371,100516488,15720.00,24,18876811,679125.0,ALLEGORIE PREMIUM BORGONA GRAND CRU,655.00,4.170028
3732,100514889,22724.00,13,30419809,516933.0,SET 8 COPAS VINUM CABERNET Y O VIOGNIER,1748.00,4.035333
696,100509358,94795.00,4,38676855,672726.0,R9 APPLE IPHONE X SP GRAY 64GB-LAE,23698.75,3.992359
5666,100514729,10528.00,20,37199104,659202.0,INDIVIDUAL BASKETWEAVE BLANCO,526.40,3.976831

In [167]:
import datetime
trash_out = r'C:\Users\Gpardo\Desktop\proyecto_test\Final_db'
save = datetime.datetime.now().strftime("%y_%m_%d")
dir = trash_out +"_"+str(save)+".xlsx"
print(dir)

writer = pd.ExcelWriter(dir, engine='xlsxwriter')

#Convert the dataframe to an XlsxWriter Excel object.
Db_sans_1.to_excel(writer, sheet_name='Sheet1')

# Close the Pandas Excel writer and output the Excel file.
writer.save()

C:\Users\Gpardo\Desktop\proyecto_test\Final_db_18_08_16.xlsx

# Recomendation Systems

In [84]:
mean_ratings = Db_sans_1.groupby(['Name'])['ratings'].mean()
mean_ratings.sort_values(ascending=False)

Name
ALLEGORIE PREMIUM BORGONA GRAND CRU         4.170028
INDIVIDUAL BASKETWEAVE BLANCO               3.976831
SERVILLETA BLANCA                           3.976831
COPA BORDEAUX                               3.768887
VASO HB GALASSIA                            3.714172
VASO 390 CLASSIC                            3.632142
COPA VINO MEDIUM 340 ML                     3.632142
COPA CHAMPAGNE MEDIUM 170 ML                3.632142
COPA BURGUNDY PUCCINI                       3.576333
COPA PARA VINO BLANCO PUCCINI               3.576333
REFRIGERADOR FDBM 42P PANELABLE KA          3.576095
PLATO SOPA 24 CM CHER BLANC                 3.512674
HYDROCONQUEST GM QZO AC CAUCHO CNGR         3.511674
39MM BISEL NEGRO GRAB GRECAS IP ORO CARA    3.511674
COPA DAILY BORDEAUX                         3.482627
RELOJ BR 126 SPORT HERITAGE RUBBER          3.481856
MYCLASS QZ ST WH 40 ST ST                   3.481856
RELOJ BR 123 ORIGINAL BEIGE CALFSKIN        3.481856
SHOT  TEQUILERO CLASSIC 70 ML               3.477523
SEVILLA COPA FLAUTA 225ML TRA               3.469180
COPA AGUA                                   3.466157
TAG CARRERA CAR ANTRA CORREA CAUCHO         3.465212
COPA CHARDONNAY                             3.442778
COPA CHEERS BORGONA                         3.437488
EGG ESTUCHE 2 COLECCIONABLES                3.430945
CAPRI VASO OF 320ML TRANSP                  3.411309
ENFRIADOR DE BEBIDAS A.INOX 24              3.403155
REFRIGERADOR BOTTOM GE 22 PIES INOX         3.392583
HORNO COMBI 60CMS EL#CTRICO GE PROFILE      3.382010
GEC.CAM.90.AI.CV966TSS                      3.382010
                                              ...
ACCESORIOS PARA CALZADO TALONERA GEL        1.436248
SEMIBODY CON REFUERZO NEGRO GRANDE          1.435647
PANTUFLA CERRADA BACON EGG  MULTICOLOR5     1.435497
CHEEKY SK STRIP TIME D VERDE AGUA,MED       1.434241
PORTAESPONJA SADDLE SINK AZUL               1.434241
CHEEKY SK STRIP TIME D SALMON,MED           1.434241
TERMO CAB PERF BOTTL 075 ENTRENASS18        1.434241
MARCADOR BLACK INK JUST ADD AZUL            1.420860
MARCADOR BLACK INK JUST ADD NARANJA         1.420860
MARCADOR BLACK INK JUST ADD PLATA           1.420860
MARCADOR BLACK INK JUST ADD VERDE           1.420860
MARCADOR BLACK INK JUST ADD VIOLETRA        1.420860
MARCADOR BLACK INK JUST ADD AMARILLO        1.420860
TANGA ROJO,MED                              1.414476
CHOCOLATE LINDOR MILK 168 G C12             1.411233
LLAVERO POP POWER RANGERS BLUE RANGER       1.380047
JGO 150 CAPACILLOS STD CORAZON              1.380047
LLAVERO POP POWER RANGERS PINK RANGER       1.380047
JUEGO FIFA 15 PS4                           1.378536
CANTIMPLORA PAW PATROL NINA                 1.366163
CANTIMPLORA CON BOTON MASHA Y EL OSO        1.366163
VASO CON TAPA HELLO KITTY                   1.366163
TAZA PORCELANA MIINNIE BLANCO               1.366163
CALCETIN CATS 1PR AZUL OBSCURO,UNI          1.341834
PROTECTOPIE WISH YOU W NEGRO,UNI            1.341834
SIMULADOR DE CARRERA DE CRUZ RAMOREZ        1.336304
POPPIT S1 REFILL PACK                       1.328905
TRUSA AZUL TURQUESA,GDE                     1.295246
JABON DE MANOS FORMA DONA                   1.223261
VM REALIDAD VIRTUAL KIT DESTINOS            1.124331
Name: ratings, Length: 5195, dtype: float64

In [85]:
ratings_by_user = Db_sans_1.groupby('UserID').size()
ratings_by_user.sort_values(ascending=False).head(10)

UserID
649025.0    25
248538.0    25
16313.0     23
158491.0    21
679955.0    18
387949.0    18
615722.0    13
440768.0    13
44593.0     13
675677.0    12
dtype: int64

In [87]:
ratings_by_name = Db_sans_1.groupby('Name').size()
ratings_by_name.sort_values(ascending=False)
#ratings_by_name[:10]

Name
CERTIFICADO DE REGALO                       82
R9 APPLE IPHONE X SILVER 64GB-LAE           40
R9 APPLE IPHONE X SP GRAY 64GB-LAE          31
GEAR S3 FRONTIER                            24
MB AIR 13 3 1 8 GHZ 8GB 128GB SPA           24
GEAR S3 CLASSIC                             24
R9 APPLE IPHONE X SP GRAY 256GB-LAE         22
JET SET ITEM MD TZ SNAP PCK NEGROS/TALL     21
NEONITO LEMUR CON EXPERIENCIA               15
CALCETIN PAQUETE 6 PIE MULTICOLOR,UNI       13
KSIMERITO ED ESP SS18 ANAROUS CON           13
CENTRO DE LAVADO GRAFITO 17 KG MABE         13
KSIMERITO ED ESP SS18 LILIPINK CON          13
BEBE MIM SAN ROSA EDICION ESPECIAL P        12
BEBE SIGOTO NEONITO PANDA                   12
RELOJ VINTAGE UNISEX DORADO                 11
BOLSO DAMA  LE PLIAGE AZUL MARINO           11
R9 APPLE IPHONE 8 PLUS SP G 64GB-LAE ESP    11
BOLSO,BEIGE BEIGE                           10
BEBE SIGOTO NEONITO CONEJA                  10
LAV SUP HE WH 19KGS 7MWTW4925EW BCO         10
APPLE WATCH S3 42 SG AL BLK SP GPS CLA       9
APPLE WATCH S3 38 GLD AL PKSD SP GPS CLA     9
R9 APPLE IPHONE X SILVER 256GB-LAE           9
MONEY PIECES TRAVEL CO CAFE CLAROS/TALL      8
BOLSO,NEGRO NEGRO                            8
TENIS COURT CHECKER BLANCO CON O,27          8
LAVADORA 18KG SUPERIOR ROJA                  8
X MEN 6IN WOLVERINE                          8
REF.14P3.WH.WT4543S.ACERO                    8
                                            ..
RELOJ SCARLETTE DAMA COMBINADO               1
RELOJ SEAMASTER 45.5 MM CO AXIAL             1
RELOJ SEIKO CABALLERO CUARZO                 1
RELOJ SIGNATUR CABALLERO AZUL                1
RELOJ NIGHT VISION 42MM QZO                  1
RELOJ SLIM RUNWAY CABALLERO NEGRO            1
RELOJ SLIM RUNWAY DAMA MORADO                1
RELOJ SMART CABALLERO PIEL CHRONO            1
RELOJ SOHO DAMA MULTICOLOR                   1
RELOJ SOHO DAMA ORO ROSADO                   1
RELOJ SPORT 43 MM QTZ BRAZ PLTA CHR          1
RELOJ OBF 38 QTZ CORR AZUL                   1
RELOJ NICO CABALLERO NEGRO                   1
RELOJ JARYN CABALLERO NEGRO                  1
RELOJ MALAGA CORR TELA VDE DAMA              1
RELOJ KAPPA CABALLERO CAFE OSCURO            1
RELOJ LADIES METALS 42 MM QTZ BRAZ PLTA      1
RELOJ LAMBDA CABALLERO PLATA                 1
RELOJ LOLA DAMA PLATA                        1
RELOJ LUIGI CABALLERO AZUL                   1
RELOJ LUIGI CABALLERO CAFE                   1
RELOJ MARINE STAR CRONO CAUCHO NEGRO         1
RELOJ NICO CABALLERO DORADO                  1
RELOJ MILITARY BLACK CABA NEGRO              1
RELOJ MINIMAL CB CJ BRZ AC CAR PT IND        1
RELOJ MODERN 34 MM QTZ BRAZ ORO R            1
RELOJ MODERN 34 MM QTZ CORR GRIS             1
RELOJ MURRAY DAMA PLATA                      1
RELOJ NICO CABALLERO CAFE OSCURO             1
012 ALOE VERDE                               1
Length: 5195, dtype: int64

In [88]:
active_users = ratings_by_user.index[ratings_by_user >= 5]
active_users[:10]

Float64Index([ 1509.0, 11922.0, 16313.0, 19967.0, 26188.0, 34681.0, 34803.0,
              40166.0, 40510.0, 44593.0],
             dtype='float64', name='UserID')

In [92]:
active_products = ratings_by_name.index[ratings_by_name >= 8]
active_products[:10]

Index(['APPLE WATCH S3 38 GLD AL PKSD SP GPS CLA',
       'APPLE WATCH S3 42 SG AL BLK SP GPS CLA',
       'BEBE MIM SAN ROSA EDICION ESPECIAL P', 'BEBE SIGOTO NEONITO CONEJA',
       'BEBE SIGOTO NEONITO PANDA', 'BOLSO DAMA  LE PLIAGE AZUL MARINO',
       'BOLSO,BEIGE BEIGE', 'BOLSO,NEGRO NEGRO',
       'CALCETIN PAQUETE 6 PIE MULTICOLOR,UNI',
       'CENTRO DE LAVADO GRAFITO 17 KG MABE'],
      dtype='object', name='Name')

In [94]:
mean_ratings.ix[active_products].sort_values(ascending=False)

C:\Users\Gpardo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

Name
R9 APPLE IPHONE X SP GRAY 64GB-LAE          3.203646
R9 APPLE IPHONE X SP GRAY 256GB-LAE         3.093851
R9 APPLE IPHONE X SILVER 256GB-LAE          3.061510
MB AIR 13 3 1 8 GHZ 8GB 128GB SPA           3.059865
R9 APPLE IPHONE X SILVER 64GB-LAE           3.054779
R9 APPLE IPHONE 8 PLUS SP G 64GB-LAE ESP    2.963905
APPLE WATCH S3 42 SG AL BLK SP GPS CLA      2.940441
CENTRO DE LAVADO GRAFITO 17 KG MABE         2.922210
APPLE WATCH S3 38 GLD AL PKSD SP GPS CLA    2.878630
LAV SUP HE WH 19KGS 7MWTW4925EW BCO         2.717327
LAVADORA 18KG SUPERIOR ROJA                 2.713131
REF.14P3.WH.WT4543S.ACERO                   2.707905
GEAR S3 CLASSIC                             2.642646
GEAR S3 FRONTIER                            2.642646
JET SET ITEM MD TZ SNAP PCK NEGROS/TALL     2.491388
MONEY PIECES TRAVEL CO CAFE CLAROS/TALL     2.457228
BOLSO DAMA  LE PLIAGE AZUL MARINO           2.420727
BOLSO,BEIGE BEIGE                           2.362487
BOLSO,NEGRO NEGRO                           2.355968
CERTIFICADO DE REGALO                       2.241356
KSIMERITO ED ESP SS18 ANAROUS CON           2.224222
KSIMERITO ED ESP SS18 LILIPINK CON          2.216801
RELOJ VINTAGE UNISEX DORADO                 2.160633
BEBE SIGOTO NEONITO CONEJA                  2.140857
TENIS COURT CHECKER BLANCO CON O,27         2.083152
BEBE MIM SAN ROSA EDICION ESPECIAL P        2.075007
BEBE SIGOTO NEONITO PANDA                   2.051743
X MEN 6IN WOLVERINE                         2.039502
TENIS CASUAL FUCSIA,24                      1.915158
NEONITO LEMUR CON EXPERIENCIA               1.877715
CALCETIN PAQUETE 6 PIE MULTICOLOR,UNI       1.686453
Name: ratings, dtype: float64

In [107]:
mean_ratings = pd.pivot_table(Db_sans_1,values=['ratings'], index=['Name'],columns=['UserID'], aggfunc='mean')
mean_ratings.head()
#mean_ratings[:10]

                                         ratings                             \
UserID                                  28.0     64.0     139.0    195.0
Name
012 ALOE VERDE                               NaN      NaN      NaN      NaN
0S SBN 2013 STARTER 123 KIT                  NaN      NaN      NaN      NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2      NaN      NaN      NaN      NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25      NaN      NaN      NaN      NaN
1460 CARPATHIAN PAJA28                       NaN      NaN      NaN      NaN

                                                                             \
UserID                                  208.0    247.0    666.0    924.0
Name
012 ALOE VERDE                               NaN      NaN      NaN      NaN
0S SBN 2013 STARTER 123 KIT                  NaN      NaN      NaN      NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2      NaN      NaN      NaN      NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25      NaN      NaN      NaN      NaN
1460 CARPATHIAN PAJA28                       NaN      NaN      NaN      NaN

                                                            ...              \
UserID                                  989.0    1066.0     ...    680713.0
Name                                                        ...
012 ALOE VERDE                               NaN      NaN   ...         NaN
0S SBN 2013 STARTER 123 KIT                  NaN      NaN   ...         NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2      NaN      NaN   ...         NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25      NaN      NaN   ...         NaN
1460 CARPATHIAN PAJA28                       NaN      NaN   ...         NaN

                                                                             \
UserID                                  680717.0 680724.0 680736.0 680764.0
Name
012 ALOE VERDE                               NaN      NaN      NaN      NaN
0S SBN 2013 STARTER 123 KIT                  NaN      NaN      NaN      NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2      NaN      NaN      NaN      NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25      NaN      NaN      NaN      NaN
1460 CARPATHIAN PAJA28                       NaN      NaN      NaN      NaN

                                                                             \
UserID                                  680770.0 680771.0 680786.0 680797.0
Name
012 ALOE VERDE                               NaN      NaN      NaN      NaN
0S SBN 2013 STARTER 123 KIT                  NaN      NaN      NaN      NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2      NaN      NaN      NaN      NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25      NaN      NaN      NaN      NaN
1460 CARPATHIAN PAJA28                       NaN      NaN      NaN      NaN


UserID                                  680812.0
Name
012 ALOE VERDE                               NaN
0S SBN 2013 STARTER 123 KIT                  NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2      NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25      NaN
1460 CARPATHIAN PAJA28                       NaN

[5 rows x 4293 columns]

In [114]:
ratings_mtx_df = pd.pivot_table(Db_sans_1,values=['ratings'], index=['UserID'],columns=['Name'])
ratings_mtx_df.ix[ratings_mtx_df.index[:15], ratings_mtx_df.columns[:15]]

C:\Users\Gpardo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

              ratings                              \
Name   012 ALOE VERDE 0S SBN 2013 STARTER 123 KIT
UserID
28.0              NaN                         NaN
64.0              NaN                         NaN
139.0             NaN                         NaN
195.0             NaN                         NaN
208.0             NaN                         NaN
247.0             NaN                         NaN
666.0             NaN                         NaN
924.0             NaN                         NaN
989.0             NaN                         NaN
1066.0            NaN                         NaN
1127.0            NaN                         NaN
1509.0            NaN                         NaN
1586.0            NaN                         NaN
1825.0            NaN                         NaN
2046.0            NaN                         NaN

                                                \
Name   12753NVPK MEMORY FOAM AZUL MARINO24 1/2
UserID
28.0                                       NaN
64.0                                       NaN
139.0                                      NaN
195.0                                      NaN
208.0                                      NaN
247.0                                      NaN
666.0                                      NaN
924.0                                      NaN
989.0                                      NaN
1066.0                                     NaN
1127.0                                     NaN
1509.0                                     NaN
1586.0                                     NaN
1825.0                                     NaN
2046.0                                     NaN

                                                                       \
Name   12753NVPK MEMORY FOAM SKE AZUL MARINO25 1460 CARPATHIAN PAJA28
UserID
28.0                                       NaN                    NaN
64.0                                       NaN                    NaN
139.0                                      NaN                    NaN
195.0                                      NaN                    NaN
208.0                                      NaN                    NaN
247.0                                      NaN                    NaN
666.0                                      NaN                    NaN
924.0                                      NaN                    NaN
989.0                                      NaN                    NaN
1066.0                                     NaN                    NaN
1127.0                                     NaN                    NaN
1509.0                                     NaN                    NaN
1586.0                                     NaN                    NaN
1825.0                                     NaN                    NaN
2046.0                                     NaN                    NaN

                                                                 \
Name   1460 W PURPLE MORADO25 19 EDT VAPO NOM RECHARGEBLE 100ML
UserID
28.0                      NaN                               NaN
64.0                      NaN                               NaN
139.0                     NaN                               NaN
195.0                     NaN                               NaN
208.0                     NaN                               NaN
247.0                     NaN                               NaN
666.0                     NaN                               NaN
924.0                     NaN                               NaN
989.0                     NaN                               NaN
1066.0                    NaN                               NaN
1127.0                    NaN                               NaN
1509.0                    NaN                               NaN
1586.0                    NaN                               NaN
1825.0                    NaN                               NaN
2046.0                    NaN                               NaN

                                                                \
Name   2 TETINA RECIEN NACIDO 1 HOYO 27X9 BOTELLA PLEGABLE SUR
UserID
28.0                             NaN                       NaN
64.0                             NaN                       NaN
139.0                            NaN                       NaN
195.0                            NaN                       NaN
208.0                            NaN                       NaN
247.0                            NaN                       NaN
666.0                            NaN                       NaN
924.0                            NaN                       NaN
989.0                            NaN                       NaN
1066.0                           NaN                       NaN
1127.0                           NaN                       NaN
1509.0                           NaN                       NaN
1586.0                           NaN                       NaN
1825.0                           NaN                       NaN
2046.0                           NaN                       NaN

                                                              \
Name   29W USB-C POWER ADAPTER-LAE 3 IN 1 TRACK JACKET KAKIL
UserID
28.0                           NaN                       NaN
64.0                           NaN                       NaN
139.0                          NaN                       NaN
195.0                          NaN                       NaN
208.0                          NaN                       NaN
247.0                          NaN                       NaN
666.0                          NaN                       NaN
924.0                          NaN                       NaN
989.0                          NaN                       NaN
1066.0                         NaN                       NaN
1127.0                         NaN                       NaN
1509.0                         NaN                       NaN
1586.0                         NaN                       NaN
1825.0                         NaN                       NaN
2046.0                         NaN                       NaN

                                                            \
Name   3 IN 1 TRACK JACKET KAKIM 3 IN 1 TRACK JACKET KAKIS
UserID
28.0                         NaN                       NaN
64.0                         NaN                       NaN
139.0                        NaN                       NaN
195.0                        NaN                       NaN
208.0                        NaN                       NaN
247.0                        NaN                       NaN
666.0                        NaN                       NaN
924.0                        NaN                       NaN
989.0                        NaN                       NaN
1066.0                       NaN                       NaN
1127.0                       NaN                       NaN
1509.0                       NaN                       NaN
1586.0                       NaN                       NaN
1825.0                       NaN                       NaN
2046.0                       NaN                       NaN


Name   3 IN 1 TRACK JACKET KAKIXL 3 PACK BOXER CK LO RISE TMULTICOLORCH
UserID
28.0                          NaN                                   NaN
64.0                          NaN                                   NaN
139.0                         NaN                                   NaN
195.0                         NaN                                   NaN
208.0                         NaN                                   NaN
247.0                         NaN                                   NaN
666.0                         NaN                                   NaN
924.0                         NaN                                   NaN
989.0                         NaN                                   NaN
1066.0                        NaN                                   NaN
1127.0                        NaN                                   NaN
1509.0                        NaN                                   NaN
1586.0                        NaN                                   NaN
1825.0                        NaN                                   NaN
2046.0                        NaN                                   NaN

In [117]:
ratings_gte_2 = ratings_mtx_df[ratings_mtx_df>=2.0]
# with an integer axis index only label-based indexing is possible

ratings_gte_2.ix[ratings_gte_2.index[:15], ratings_gte_2.columns[:15]]

C:\Users\Gpardo\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

              ratings                              \
Name   012 ALOE VERDE 0S SBN 2013 STARTER 123 KIT
UserID
28.0              NaN                         NaN
64.0              NaN                         NaN
139.0             NaN                         NaN
195.0             NaN                         NaN
208.0             NaN                         NaN
247.0             NaN                         NaN
666.0             NaN                         NaN
924.0             NaN                         NaN
989.0             NaN                         NaN
1066.0            NaN                         NaN
1127.0            NaN                         NaN
1509.0            NaN                         NaN
1586.0            NaN                         NaN
1825.0            NaN                         NaN
2046.0            NaN                         NaN

                                                \
Name   12753NVPK MEMORY FOAM AZUL MARINO24 1/2
UserID
28.0                                       NaN
64.0                                       NaN
139.0                                      NaN
195.0                                      NaN
208.0                                      NaN
247.0                                      NaN
666.0                                      NaN
924.0                                      NaN
989.0                                      NaN
1066.0                                     NaN
1127.0                                     NaN
1509.0                                     NaN
1586.0                                     NaN
1825.0                                     NaN
2046.0                                     NaN

                                                                       \
Name   12753NVPK MEMORY FOAM SKE AZUL MARINO25 1460 CARPATHIAN PAJA28
UserID
28.0                                       NaN                    NaN
64.0                                       NaN                    NaN
139.0                                      NaN                    NaN
195.0                                      NaN                    NaN
208.0                                      NaN                    NaN
247.0                                      NaN                    NaN
666.0                                      NaN                    NaN
924.0                                      NaN                    NaN
989.0                                      NaN                    NaN
1066.0                                     NaN                    NaN
1127.0                                     NaN                    NaN
1509.0                                     NaN                    NaN
1586.0                                     NaN                    NaN
1825.0                                     NaN                    NaN
2046.0                                     NaN                    NaN

                                                                 \
Name   1460 W PURPLE MORADO25 19 EDT VAPO NOM RECHARGEBLE 100ML
UserID
28.0                      NaN                               NaN
64.0                      NaN                               NaN
139.0                     NaN                               NaN
195.0                     NaN                               NaN
208.0                     NaN                               NaN
247.0                     NaN                               NaN
666.0                     NaN                               NaN
924.0                     NaN                               NaN
989.0                     NaN                               NaN
1066.0                    NaN                               NaN
1127.0                    NaN                               NaN
1509.0                    NaN                               NaN
1586.0                    NaN                               NaN
1825.0                    NaN                               NaN
2046.0                    NaN                               NaN

                                                                \
Name   2 TETINA RECIEN NACIDO 1 HOYO 27X9 BOTELLA PLEGABLE SUR
UserID
28.0                             NaN                       NaN
64.0                             NaN                       NaN
139.0                            NaN                       NaN
195.0                            NaN                       NaN
208.0                            NaN                       NaN
247.0                            NaN                       NaN
666.0                            NaN                       NaN
924.0                            NaN                       NaN
989.0                            NaN                       NaN
1066.0                           NaN                       NaN
1127.0                           NaN                       NaN
1509.0                           NaN                       NaN
1586.0                           NaN                       NaN
1825.0                           NaN                       NaN
2046.0                           NaN                       NaN

                                                              \
Name   29W USB-C POWER ADAPTER-LAE 3 IN 1 TRACK JACKET KAKIL
UserID
28.0                           NaN                       NaN
64.0                           NaN                       NaN
139.0                          NaN                       NaN
195.0                          NaN                       NaN
208.0                          NaN                       NaN
247.0                          NaN                       NaN
666.0                          NaN                       NaN
924.0                          NaN                       NaN
989.0                          NaN                       NaN
1066.0                         NaN                       NaN
1127.0                         NaN                       NaN
1509.0                         NaN                       NaN
1586.0                         NaN                       NaN
1825.0                         NaN                       NaN
2046.0                         NaN                       NaN

                                                            \
Name   3 IN 1 TRACK JACKET KAKIM 3 IN 1 TRACK JACKET KAKIS
UserID
28.0                         NaN                       NaN
64.0                         NaN                       NaN
139.0                        NaN                       NaN
195.0                        NaN                       NaN
208.0                        NaN                       NaN
247.0                        NaN                       NaN
666.0                        NaN                       NaN
924.0                        NaN                       NaN
989.0                        NaN                       NaN
1066.0                       NaN                       NaN
1127.0                       NaN                       NaN
1509.0                       NaN                       NaN
1586.0                       NaN                       NaN
1825.0                       NaN                       NaN
2046.0                       NaN                       NaN


Name   3 IN 1 TRACK JACKET KAKIXL 3 PACK BOXER CK LO RISE TMULTICOLORCH
UserID
28.0                          NaN                                   NaN
64.0                          NaN                                   NaN
139.0                         NaN                                   NaN
195.0                         NaN                                   NaN
208.0                         NaN                                   NaN
247.0                         NaN                                   NaN
666.0                         NaN                                   NaN
924.0                         NaN                                   NaN
989.0                         NaN                                   NaN
1066.0                        NaN                                   NaN
1127.0                        NaN                                   NaN
1509.0                        NaN                                   NaN
1586.0                        NaN                                   NaN
1825.0                        NaN                                   NaN
2046.0                        NaN                                   NaN

In [118]:
ratings_gte_4_pd = pd.DataFrame({'total': ratings_mtx_df.count(), 'gte_4': ratings_gte_2.count()})
ratings_gte_4_pd.head(10)

                                                 total  gte_4
        Name
ratings 012 ALOE VERDE                               1      1
        0S SBN 2013 STARTER 123 KIT                  1      1
        12753NVPK MEMORY FOAM AZUL MARINO24 1/2      1      1
        12753NVPK MEMORY FOAM SKE AZUL MARINO25      1      0
        1460 CARPATHIAN PAJA28                       2      2
        1460 W PURPLE MORADO25                       1      1
        19 EDT VAPO NOM RECHARGEBLE 100ML            1      1
        2 TETINA RECIEN NACIDO 1 HOYO                1      1
        27X9 BOTELLA PLEGABLE SUR                    1      0
        29W USB-C POWER ADAPTER-LAE                  1      0

In [119]:
ratings_gte_4_pd['gte_4_ratio'] = (ratings_gte_4_pd['gte_4'] * 1.0)/ ratings_gte_4_pd.total
ratings_gte_4_pd.head(10)

                                                 total  gte_4  gte_4_ratio
        Name
ratings 012 ALOE VERDE                               1      1          1.0
        0S SBN 2013 STARTER 123 KIT                  1      1          1.0
        12753NVPK MEMORY FOAM AZUL MARINO24 1/2      1      1          1.0
        12753NVPK MEMORY FOAM SKE AZUL MARINO25      1      0          0.0
        1460 CARPATHIAN PAJA28                       2      2          1.0
        1460 W PURPLE MORADO25                       1      1          1.0
        19 EDT VAPO NOM RECHARGEBLE 100ML            1      1          1.0
        2 TETINA RECIEN NACIDO 1 HOYO                1      1          1.0
        27X9 BOTELLA PLEGABLE SUR                    1      0          0.0
        29W USB-C POWER ADAPTER-LAE                  1      0          0.0

In [121]:
ranking = [(title,total,gte_4, score) for title, total, gte_4, score in ratings_gte_4_pd.itertuples()]

for title, total, gte_4, score in sorted(ranking, key=lambda x: (x[3], x[2], x[1])  , reverse=True)[:10]:
    print(title, total, gte_4, score)

('ratings', 'R9 APPLE IPHONE X SILVER\xa064GB-LAE') 33 33 1.0
('ratings', 'R9 APPLE IPHONE X SP GRAY\xa064GB-LAE') 26 26 1.0
('ratings', 'GEAR S3 CLASSIC') 24 24 1.0
('ratings', 'GEAR S3 FRONTIER') 24 24 1.0
('ratings', 'MB AIR 13 3 1 8 GHZ 8GB 128GB SPA') 24 24 1.0
('ratings', 'JET SET ITEM MD TZ SNAP PCK NEGROS/TALL') 21 21 1.0
('ratings', 'R9 APPLE IPHONE X SP GRAY 256GB-LAE') 20 20 1.0
('ratings', 'CENTRO DE LAVADO GRAFITO 17 KG MABE') 13 13 1.0
('ratings', 'BOLSO DAMA  LE PLIAGE AZUL MARINO') 11 11 1.0
('ratings', 'R9 APPLE IPHONE 8 PLUS SP G 64GB-LAE ESP') 11 11 1.0

In [124]:
ratings_by_title = Db_sans_1.groupby('Name').size()
ratings_by_title.sort_values(ascending=False)[:10]

Name
CERTIFICADO DE REGALO                      82
R9 APPLE IPHONE X SILVER 64GB-LAE          40
R9 APPLE IPHONE X SP GRAY 64GB-LAE         31
GEAR S3 FRONTIER                           24
MB AIR 13 3 1 8 GHZ 8GB 128GB SPA          24
GEAR S3 CLASSIC                            24
R9 APPLE IPHONE X SP GRAY 256GB-LAE        22
JET SET ITEM MD TZ SNAP PCK NEGROS/TALL    21
NEONITO LEMUR CON EXPERIENCIA              15
CALCETIN PAQUETE 6 PIE MULTICOLOR,UNI      13
dtype: int64

In [125]:
for title, total, gte_4, score in sorted(ranking, key=lambda x: (x[2], x[3], x[1])  , reverse=True)[:10]:
    print (title, total, gte_4, score)

('ratings', 'CERTIFICADO DE REGALO') 76 68 0.8947368421052632
('ratings', 'R9 APPLE IPHONE X SILVER\xa064GB-LAE') 33 33 1.0
('ratings', 'R9 APPLE IPHONE X SP GRAY\xa064GB-LAE') 26 26 1.0
('ratings', 'GEAR S3 CLASSIC') 24 24 1.0
('ratings', 'GEAR S3 FRONTIER') 24 24 1.0
('ratings', 'MB AIR 13 3 1 8 GHZ 8GB 128GB SPA') 24 24 1.0
('ratings', 'JET SET ITEM MD TZ SNAP PCK NEGROS/TALL') 21 21 1.0
('ratings', 'R9 APPLE IPHONE X SP GRAY 256GB-LAE') 20 20 1.0
('ratings', 'CENTRO DE LAVADO GRAFITO 17 KG MABE') 13 13 1.0
('ratings', 'KSIMERITO ED ESP SS18 LILIPINK CON') 13 12 0.9230769230769231

In [127]:
product_users = pd.pivot_table(Db_sans_1,values=['ratings'], index=['Name'],columns=['UserID'])
product_users.ix[product_users.index[:15], product_users.columns[:15]]

C:\Users\Gpardo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

                                        ratings                              \
UserID                                   28.0   64.0   139.0  195.0  208.0
Name
012 ALOE VERDE                              NaN    NaN    NaN    NaN    NaN
0S SBN 2013 STARTER 123 KIT                 NaN    NaN    NaN    NaN    NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2     NaN    NaN    NaN    NaN    NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25     NaN    NaN    NaN    NaN    NaN
1460 CARPATHIAN PAJA28                      NaN    NaN    NaN    NaN    NaN
1460 W PURPLE MORADO25                      NaN    NaN    NaN    NaN    NaN
19 EDT VAPO NOM RECHARGEBLE 100ML           NaN    NaN    NaN    NaN    NaN
2 TETINA RECIEN NACIDO 1 HOYO               NaN    NaN    NaN    NaN    NaN
27X9 BOTELLA PLEGABLE SUR                   NaN    NaN    NaN    NaN    NaN
29W USB-C POWER ADAPTER-LAE                 NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIL                   NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIM                   NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIS                   NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIXL                  NaN    NaN    NaN    NaN    NaN
3 PACK BOXER CK LO RISE TMULTICOLORCH       NaN    NaN    NaN    NaN    NaN

                                                                            \
UserID                                  247.0  666.0  924.0  989.0  1066.0
Name
012 ALOE VERDE                             NaN    NaN    NaN    NaN    NaN
0S SBN 2013 STARTER 123 KIT                NaN    NaN    NaN    NaN    NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2    NaN    NaN    NaN    NaN    NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25    NaN    NaN    NaN    NaN    NaN
1460 CARPATHIAN PAJA28                     NaN    NaN    NaN    NaN    NaN
1460 W PURPLE MORADO25                     NaN    NaN    NaN    NaN    NaN
19 EDT VAPO NOM RECHARGEBLE 100ML          NaN    NaN    NaN    NaN    NaN
2 TETINA RECIEN NACIDO 1 HOYO              NaN    NaN    NaN    NaN    NaN
27X9 BOTELLA PLEGABLE SUR                  NaN    NaN    NaN    NaN    NaN
29W USB-C POWER ADAPTER-LAE                NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIL                  NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIM                  NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIS                  NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIXL                 NaN    NaN    NaN    NaN    NaN
3 PACK BOXER CK LO RISE TMULTICOLORCH      NaN    NaN    NaN    NaN    NaN


UserID                                  1127.0 1509.0 1586.0 1825.0 2046.0
Name
012 ALOE VERDE                             NaN    NaN    NaN    NaN    NaN
0S SBN 2013 STARTER 123 KIT                NaN    NaN    NaN    NaN    NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2    NaN    NaN    NaN    NaN    NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25    NaN    NaN    NaN    NaN    NaN
1460 CARPATHIAN PAJA28                     NaN    NaN    NaN    NaN    NaN
1460 W PURPLE MORADO25                     NaN    NaN    NaN    NaN    NaN
19 EDT VAPO NOM RECHARGEBLE 100ML          NaN    NaN    NaN    NaN    NaN
2 TETINA RECIEN NACIDO 1 HOYO              NaN    NaN    NaN    NaN    NaN
27X9 BOTELLA PLEGABLE SUR                  NaN    NaN    NaN    NaN    NaN
29W USB-C POWER ADAPTER-LAE                NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIL                  NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIM                  NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIS                  NaN    NaN    NaN    NaN    NaN
3 IN 1 TRACK JACKET KAKIXL                 NaN    NaN    NaN    NaN    NaN
3 PACK BOXER CK LO RISE TMULTICOLORCH      NaN    NaN    NaN    NaN    NaN

In [133]:
ratings_by_product = Db_sans_1[Db_sans_1['Name'] == 'GEAR S3 CLASSIC']
ratings_by_product.set_index('UserID', inplace=True)
ratings_by_product

,ID,Transaction_Revenue,qty,SKU,Name,price,ratings
UserID,,,,,,,
32097.0,100378459,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
670506.0,100507425,6649.05,1,37774766,GEAR S3 CLASSIC,6649.05,2.640669
672864.0,100509448,6649.05,1,37774766,GEAR S3 CLASSIC,6649.05,2.640669
531927.0,100510135,6649.05,1,37774766,GEAR S3 CLASSIC,6649.05,2.640669
674028.0,100510963,6649.05,1,37774766,GEAR S3 CLASSIC,6649.05,2.640669
49939.0,100511239,6649.05,1,37774766,GEAR S3 CLASSIC,6649.05,2.640669
674539.0,100511391,27247.88,1,37774766,GEAR S3 CLASSIC,27247.88,3.063819
137908.0,100512729,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
553497.0,100512804,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
676537.0,100513586,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
676985.0,100513865,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
270082.0,100513907,11338.38,2,37774766,GEAR S3 CLASSIC,5669.19,3.078043
677088.0,100513969,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
36357.0,100514047,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
672691.0,100515651,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
678463.0,100515749,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
679278.0,100516692,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
680594.0,100518161,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
680616.0,100518177,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
680681.0,100518248,5669.19,1,37774766,GEAR S3 CLASSIC,5669.19,2.592840
344368.0,100513499,5669.19,1,37774767,GEAR S3 CLASSIC,5669.19,2.592840
233645.0,100515632,5669.19,1,37774767,GEAR S3 CLASSIC,5669.19,2.592840
679236.0,100516663,5669.19,1,37774767,GEAR S3 CLASSIC,5669.19,2.592840
679941.0,100517451,5669.19,1,37774767,GEAR S3 CLASSIC,5669.19,2.592840

In [161]:
product_userst= product_users[('ratings')]
their_ids = ratings_by_product.index
their_ratings = product_userst[their_ids]
product_userst[their_ids].ix[product_userst[their_ids].index[:15], product_userst[their_ids].columns[:15]]

C:\Users\Gpardo\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

UserID,32097.0,670506.0,672864.0,531927.0,674028.0,49939.0,674539.0,137908.0,553497.0,676537.0,676985.0,270082.0,677088.0,36357.0,672691.0
Name,,,,,,,,,,,,,,,
012 ALOE VERDE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0S SBN 2013 STARTER 123 KIT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12753NVPK MEMORY FOAM AZUL MARINO24 1/2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12753NVPK MEMORY FOAM SKE AZUL MARINO25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1460 CARPATHIAN PAJA28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1460 W PURPLE MORADO25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19 EDT VAPO NOM RECHARGEBLE 100ML,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2 TETINA RECIEN NACIDO 1 HOYO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27X9 BOTELLA PLEGABLE SUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29W USB-C POWER ADAPTER-LAE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3 IN 1 TRACK JACKET KAKIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3 IN 1 TRACK JACKET KAKIM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3 IN 1 TRACK JACKET KAKIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3 IN 1 TRACK JACKET KAKIXL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3 PACK BOXER CK LO RISE TMULTICOLORCH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [163]:
product_count =  their_ratings.ix['GEAR S3 CLASSIC'].count()
sims = their_ratings.apply(lambda profile: profile.count() / float(product_count) , axis=1)

C:\Users\Gpardo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

In [164]:
sims.sort_values(ascending=False)[1:][:10]

Name
GEAR S3 FRONTIER                   1.000000
SET 5 CONTENEDORES INGENIO         0.041667
MARIO KART 8 YOSHI                 0.041667
MARIO KART DONKEY KONG KART        0.041667
PEUGEOT RED BULL DAKAR 16          0.041667
MARIO KART 8 MARIO                 0.041667
CARTERA CHANTACO NEGRO             0.041667
EV FERRARI SF 15T SVETTEL NO05     0.041667
MARIO KART 8 PEACH                 0.041667
MERCEDES BENZ ENERGFORCE POLICE    0.041667
dtype: float64

In [ ]:
!conda install -c conda-forge scikit-surprise

In [ ]:


from surprise import NormalPredictor
from surprise import Dataset
from surprise import Reader
from surprise.model_selection import cross_validate